//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TataruLink.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TataruLink.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Types.
        /// </summary>
        internal static string ConfigTabChatTypes {
            get {
                return ResourceManager.GetString("ConfigTabChatTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string ConfigTabGeneral {
            get {
                return ResourceManager.GetString("ConfigTabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TataruLink Settings.
        /// </summary>
        internal static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Keys.
        /// </summary>
        internal static string GeneralAPIKeys {
            get {
                return ResourceManager.GetString("GeneralAPIKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepL API Key.
        /// </summary>
        internal static string GeneralDeepLKey {
            get {
                return ResourceManager.GetString("GeneralDeepLKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Automatic Chat Translation.
        /// </summary>
        internal static string GeneralEnableAutoChat {
            get {
                return ResourceManager.GetString("GeneralEnableAutoChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Language Detection.
        /// </summary>
        internal static string GeneralEnableLangDetect {
            get {
                return ResourceManager.GetString("GeneralEnableLangDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Translations.
        /// </summary>
        internal static string GeneralEnableTranslations {
            get {
                return ResourceManager.GetString("GeneralEnableTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine.
        /// </summary>
        internal static string GeneralEngine {
            get {
                return ResourceManager.GetString("GeneralEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Language.
        /// </summary>
        internal static string GeneralFromLanguage {
            get {
                return ResourceManager.GetString("GeneralFromLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate My Own Messages.
        /// </summary>
        internal static string GeneralTranslateOwn {
            get {
                return ResourceManager.GetString("GeneralTranslateOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate To.
        /// </summary>
        internal static string GeneralTranslateTo {
            get {
                return ResourceManager.GetString("GeneralTranslateTo", resourceCulture);
            }
        }
    }
}
